service: python
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem

          Resource:
            - arn:aws:dynamodb:us-east-1:${aws:accountId}:table/User

functions:
  get-user:
    handler: handler.lambda_handler
    events:
      - httpApi:
          path: /users/{id}
          method: get